MLP implementation
UVA-LavaLab/PIMeval-PIMbench pull request #54
Opened 2024-07-24 20:37 UTC by kmd2zjw

2024-07-24 20:54 UTC, fasiddique requested changes

2024-07-24 20:54 UTC, fasiddique commented on misc-bench/cpp-mlp/mlp.cpp
> +    }
can you please update this with new gemv implementation?

2024-09-11 06:39 UTC, deyuan commented on misc-bench/cpp-mlp/PIM/Makefile
> +	rm -rf $(EXEC) *.dSYM
Missing line break at the end of file

2024-09-11 06:40 UTC, deyuan commented on misc-bench/cpp-mlp/baselines/mlp.py
> +    main(args)
Missing line break at the end of file

2024-09-11 06:41 UTC, deyuan commented on misc-bench/cpp-mlp/PIM/mlp.cpp
> +using namespace std;
One suggestion is to not using this, and explicitly write std:: in code

2024-09-11 06:42 UTC, deyuan commented on misc-bench/cpp-mlp/PIM/mlp.cpp
> +#define T int32_t
Suggest a more comprehensive type name to ease searching

2024-09-11 06:45 UTC, deyuan commented on misc-bench/cpp-mlp/PIM/mlp.cpp
> +
Missing file header and license info

2024-09-11 06:47 UTC, deyuan commented on misc-bench/cpp-mlp/baselines/mlp.py
> +import sys
Missing file header

2024-09-11 06:48 UTC, deyuan reviewed
Hi @kmd2zjw I've added a few comments. Could you take a look?

2024-09-11 11:03 UTC, closed without merging

2024-09-11 11:06 UTC, kmd2zjw commented
This is an outdated PR, but I implemented most of your suggestions. The finalized MLP needs to implement batched GEMM, which I'm still waiting to be fully finished and pushed. The part that isn't finished is listed here in a comment in the batched gemm pim file:

// Concatenate matrices. Needs to be done once
  std::vector<std::vector<int>> batchedSrcMatA;
  for (uint64_t i = 0; i < colA; ++i)
  {
    std::vector<int> temp;
    for (uint64_t j = 0; j < batchSize; ++j) {
      // TODO: Add replicate a pattern API in the simulator
      for (uint64_t k = 0; k < row; ++k) {
        temp.push_back(srcMatrixAT[i][k]);
      }
    }
    batchedSrcMatA.push_back(temp);
  }